### ISSUE TITLE
Missing setBusinessHoursList() for the picker

### ISSUE THREAD

**Issue by shailevy2** [bashizip/business-hours-picker#1]
The picker needs to have a setBusinessHoursList() otherwise editing select hours becomes a manner of reentering all past values

**Comment by bashizip** [comment]
YES !  Will be available very soon, keep in touch. Or do a PR ?

**Comment by shailevy2** [comment]
Keep in touch :)
Close the issue when published, thanks ...

**Comment by alezoffoli** [comment]
hi @bashizip, just wondering if you had the chance to look into this. anyway, congrats for the hard work!

**Comment by bashizip** [comment]
Please use the new release :  

`implementation 'com.github.bashizip:business-hours-picker:1.1.1'`

Thanks!

**Comment by alezoffoli** [comment]
wow, nice, will try out!
