### ISSUE TITLE
Cannot resolve library

### ISSUE THREAD

**Issue by BuraqsysStudio** [bashizip/business-hours-picker#2]
Failed to resolve: com.github.bashizip:business-hours-picker:1.1.0

I am having a strange issue. I am adding this library for Business Hour Picking.

But strangely the older versions are added with no issues. But when I add the latest one it is not resolving by gradle.

I have tried:

Clean Project

Rebuilt It

Invalidate Cache & Restart

But i can't add the library.

**Comment by bashizip** [comment]
Hi,

Try this one : implementation 'com.github.bashizip:business-hours-picker:v.1.1.0'

You missed the "v".
