### ISSUE TITLE
add dependencie in tutorial (Readme)

### ISSUE THREAD

**Issue by matheusbrunetti** [bashizip/business-hours-picker#4]
I was getting some trouble when try to import like the readme this library.
Then, I found a way using the following link to get the correct form for implementation: [https://jitpack.io/#bashizip/business-hours-picker/v.1.1.0](url)

So, the correct way to import it is using the following code: 
`implementation 'com.github.bashizip:business-hours-picker:v.1.1.0'`

**Comment by bashizip** [comment]
Thank you for pointing this out ! It's something I wished I had more time to fix. Now it's done.
The next releases will not the the v prefix !
